services:
  backend:
    build:
      context: ./backend
    container_name: ecgtwinmentor-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MODEL_PATH=model.tflite
      - USERS_FILE=users.json
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecgtwinmentor-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
